version: '3'

networks:
  backend:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: paystar_nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - backend
  mysql:
    image: mysql:8.0
    container_name: paystar_mysql
    volumes:
      - ./mysql:/var/liv/mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_DATABASE=paystar_db"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    networks:
      - backend
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paystar_php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - backend
  composer:
    image: composer:latest
    container_name: paystar_composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - backend
  npm:
    image: node:13.7
    container_name: paystar_npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ 'npm' ]
  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paystar_artisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: [ 'php','/var/www/html/artisan' ]
    networks:
      - backend